### ISSUE TITLE
Transform from wfc_dm_2d.dm_gamma to LOC.DM

### ISSUE THREAD

**Issue by Qx80610702** [abacusmodeling/abacus-develop#102]
In the GAMMA_ONLY line, there is a function "cal_dk_gamma_from_2D" to transform wfc_dm_2d.dm_gamma to LOC.DM, how to transform wfc_dm_2d.dm_k to LOC.DM_R in k-points line?

**Comment by dyzheng** [comment]
Multi-k and gamma_only line should use same method for that.
We will refactor this part.
