### ISSUE TITLE
Error message: some processor has no bands-row-blocks.

### ISSUE THREAD

**Issue by LiuXiaohui123321** [abacusmodeling/abacus-develop#126]
When calculating the example attached with **abacus v2.2.0**, I met the error of "some processor has no bands-row-blocks."
![1650270973(1)](https://user-images.githubusercontent.com/25027983/163781734-911e1731-164c-4aa5-aa37-4fad367d5b37.jpg)

If I change to use **v2.1.0**, no error;
And if I change the number of cpu cores from 40 to 16, no error either.
[lcao-error_bands-row-blocks.zip](https://github.com/abacusmodeling/abacus-develop/files/8504708/lcao-error_bands-row-blocks.zip)

**Comment by dyzheng** [comment]
I have fixed this bug, when the problem occured, program will auto set nb2d as 1 and then reallocate the matrix.
