### ISSUE TITLE
Lack of some output in md calculation with pw basis

### ISSUE THREAD

**Issue by LiuXiaohui123321** [abacusmodeling/abacus-develop#127]
In md calculation with pw basis, one line of output information is missing now:
** ITER   ETOT(eV)       EDIFF(eV)      SCF_THR    CG_ITER    TIME(S)**
![1650276916](https://user-images.githubusercontent.com/25027983/163794211-ad4a461d-7d43-451a-8dfe-d13e22f0941a.jpg)

**Comment by dyzheng** [comment]
[https://github.com/deepmodeling/abacus-develop/pull/857](url) In this PR, we have fixed this bug. Thanks for your report!
