### ISSUE TITLE
Useless output in warning.log when using upf201 pseudopot: In SCAN_BEGIN, can't find: xxx block.

### ISSUE THREAD

**Issue by LiuXiaohui123321** [abacusmodeling/abacus-develop#128]
Maybe there is something wrong in function `Pseudopot_upf::read_pseudo_upf201()`.
When using upf201 pseudopot, there will be useless output in the file of warning.log.
![1650332612(1)](https://user-images.githubusercontent.com/25027983/163904209-b2da2f76-7dcc-4aac-849f-77008048dfd7.jpg)

**Comment by dyzheng** [comment]
@LiuXiaohui123321 If this Issue has been solved?

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
