### ISSUE TITLE
Difference in the calculation results (total energy and charge density) between v2.2.0 and v2.1.0

### ISSUE THREAD

**Issue by LiuXiaohui123321** [abacusmodeling/abacus-develop#129]
There are some differences in the calculation results between v2.2.0 and v2.1.0.
For example, a system with 64 Si atoms,
**Total Energy**
|  | Total energy (eV) |
| :-----: | :----: |
| v2.1.0 (genelpa) | -6886.141105681941 |
| v2.2.0 (genelpa) | -6886.143459123970 |
| v2.2.0 (scalapack) | -6886.143459124583 |

**Charge Density**
![Si64](https://user-images.githubusercontent.com/25027983/164158438-7621a04d-b6c9-4aa4-8b08-2629c50d738f.jpg)

Other systems, like with 128/256/512/1024 Si  atoms, have the same problem. Please refer to the attached files.
[results_difference.zip](https://github.com/abacusmodeling/abacus-develop/files/8518587/results_difference.zip)

**Comment by pxlxingliang** [comment]
In V2.2.0, the energies solved by ELPA and SCALPACK are close (the difference is only ~1e-9), which indicates the results are reliable. The large difference of ELPA between two version may be aroused from the wrong implement of ELPA V2.1.0 or the H matrix in these two version are different. @dyzheng says that the construction of H matrix are different in V2.1.0 and V2.2.0, and this should make the difference of the final energy.

**Comment by LiuXiaohui123321** [comment]
@pxlxingliang Thank you for your reply. 
For the example above, the energies solved by ELPA and SCALPACK are close. And for another example with 256 Si atoms, if calculated using 16cores, the energies and charge density solved by ELPA and SCALPACK are almost the same.
**Total Energy**
| | Total energy (eV) |
| :---: | :--- |
| genelpa | -27570.62741550360 |
| scalapck | -27570.62741550344 |

**Charge Densiy**
![1650444954](https://user-images.githubusercontent.com/25027983/164191111-ac965def-7221-4e69-a939-2059be65953f.jpg)

If calculated using 40cores, the energies solved by ELPA and SCALPACK are still almost the same
**Total Energy**
| | Total energy (eV) |
| :---: | :--- |
| genelpa | -27570.62741550347 |
| scalapck | -27570.62741550409 |

But the charge density are different after some scf iterations.
**Charge Densiy**
![1650445392(1)](https://user-images.githubusercontent.com/25027983/164192419-df1e21a1-e48d-46e3-9d12-2bfdb8162cb5.jpg)

So, I think there are two problems here:

1. The new version of ELPA implemented in abacus v2.2.0 is not stable, because if using different number of cpu cores, the results (charge density) are different;
2. The results (total energy and charge density) between v2.2.0 and v2.1.0 are different, which may be aroused from the H matrix in these two versions are different. We'd better explicitly find out which changes are causing these differences. @dyzheng

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
