### ISSUE TITLE
Eu pseudopotential converted from CP2K GTH format cannot used by ABACUS

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#137]
## Describe the Bug
I used an Eu pseudopotential converted from CP2K GTH format to run ABACUS, but some errors reported:

1.  ABACUS reads parameter of <PP_BETA> named `cutoff_radius_index` in the UPF file, which can be deduced from `module_cell/read_pp_upf201.cpp:208`. However, `cutoff_radius_index` is not set in Eu pseudopotential file, I guess this parameter may not be necessary. To overcome this, I set the `cutoff_radius_index` in this Eu pseudopotential file manually, then another question raised.

2. The job failed with error:
```
ABACUS.mpi: ./src_pw/charge.cpp:256: lambda []()->std::vector<double, std::allocator<double>>::operator()()->std::vector<double, std::allocator<double>>: Assertion \`charge!=0.0 || charge==atom->zv\' failed.
```
And I checked the `charge`,  its output was zero.

Then I used Quantum Espresso to test this UPF file, the job finished successfully, though  the parameter `cutoff_radius_index` was not set.

## Expected behavior
The job finishes successfully.

## To Reproduce
1. Attached file is 'PROJECT-Eu.UPF-1.txt' in which the the parameter `cutoff_radius_index` is set by myself.  And original set of pseudopotential files can be obtained from [https://github.com/simonpintarelli/lanthanides-nc-pseudos](url)
2. The example for this test is a simple system of two Eu atoms
4. SCF calculation with PW basis

## Version
- ABACUS: `develop` branch of [https://github.com/abacusmodeling/abacus-develop](url)
- QE: version 6.2.1

## Additional Context
[PROJECT-Eu.UPF-1.txt](https://github.com/abacusmodeling/abacus-develop/files/8646821/PROJECT-Eu.UPF-1.txt)

**Comment by sunliang98** [comment]
Could you provide the complete example, including `INPUT`, `STRU`, and `KPT`, as well as corresponding results of QE, so that I can determine if the problem is solved or not?

**Comment by 1041176461** [comment]
@sunliang98 

[Eu.zip](https://github.com/abacusmodeling/abacus-develop/files/8660098/Eu.zip)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
