### ISSUE TITLE
how to choose a good parameter to calculate the  MD interface structure faster with more than 500 atoms ?

### ISSUE THREAD

**Issue by lzcun** [abacusmodeling/abacus-develop#141]
dear prof.
Now I am simulating the MD of the interface structure. At present, it takes a long time to calculate the system of about 500 atoms.  And the interface is LiCoO2-Li6PS5Cl. 
After 4 steps, it needs 23 electronic steps for each ion step.  Only 50 ion steps can be calculated in a day if I use 160 cores. 
Below are the parameters I used in the INPUT and .log files:

[INPUT.txt](https://github.com/abacusmodeling/abacus-develop/files/8735828/INPUT.txt)
[job-5204013.log](https://github.com/abacusmodeling/abacus-develop/files/8735838/job-5204013.log)
(but running.log file can't upload)
If I use more cores, the program would be killed or don't work.
How to choose an excellent parameter to calculate the interface structure faster with more than 500 atoms?

**Comment by mohanchen** [comment]
Which version of the code did you use? Typically we don't suggest running MD simulations for systems over 500 atoms (size is a bit large).

**Comment by lzcun** [comment]
> Which version of the code did you use? Typically we don't suggest running MD simulations for systems over 500 atoms (size is a bit large).

Thanks for your reply,  Prf. Chen, the version I used is 2.2.1. If I want to simulate MD of a large system, will we batter use DPMD?

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
