### ISSUE TITLE
Compilation error w/ latest elpa code

### ISSUE THREAD

**Issue by YaoYinYing** [abacusmodeling/abacus-develop#147]
Hi

I run the installation of elpa lib by clone the official repo (https://gitlab.mpcdf.mpg.de/elpa/elpa) and compile it w/ the following options:
```shell
--enable-openmp --enable-nvidia-gpu --with-mpi=yes CFLAGS='-mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -maes -mavx -mfma -mavx2 -mavx512f -mavx512cd -mavx512vl -mavx512bw -mavx512dq'
```
and the destination dir locates at `/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e`

then i simply run command of abacus installation:
```shell
cmake -B build -DCMAKE_INSTALL_PREFIX=/software/abacus/2.2.3/  -DUSE_LIBXC=1 -DUSE_CUDA=1 -DELPA_LIBRARY=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e/lib/ -DELPA_INCLUDE_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e/include/elpa_openmp-2022.05.001.rc1/

cmake --build build -j19
cmake --install build
```
and the error occurs:
```test
[100%] Built target pw
[100%] Built target ri
[100%] Built target io
Scanning dependencies of target abacus
[100%] Building CXX object CMakeFiles/abacus.dir/source/main.cpp.o
[100%] Linking CXX executable abacus
/usr/bin/ld: cannot find /software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e/lib: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/abacus.dir/build.make:931: abacus] Error 1
make[1]: *** [CMakeFiles/Makefile2:618: CMakeFiles/abacus.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Can somebody please help me with that?

**Comment by caic99** [comment]
> Hi @YaoYinYing , Would you try defining `-DELPA_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e` when configuring using `cmake`? [Here](https://github.com/deepmodeling/abacus-develop/blob/develop/Dockerfile.gnu#L26-L31) is a reference for you to install elpa.

And, I noticed that you are using `--enable-nvidia-gpu` flag when compiling ELPA. We didn't test if it works fine with ABACUS.

**Comment by YaoYinYing** [comment]
@caic99 Thank you for your fast reply! i recomplied elpa by the option in the dockerfile and build abacus w/ `-DELPA_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e -DELPA_INCLUDE_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e/include/elpa-2022.05.001.rc1`, and it finally works!

**Comment by caic99** [comment]
> @caic99 Thank you for your fast reply! i recomplied elpa by the option in the dockerfile and build abacus w/ `-DELPA_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e -DELPA_INCLUDE_DIR=/software/elpa/commit_d6dacc08bc1729583308d2ac6cef7211d3113b4e/include/elpa-2022.05.001.rc1`, and it finally works!

For installing ABACUS, please refer to our [instructions](https://github.com/deepmodeling/abacus-develop/blob/develop/docs/install.md#build-and-install-abacus-with-cmake). Actually, you don't need `-DELPA_INCLUDE_DIR` here, ELPA_DIR would work fine.
