### ISSUE TITLE
Bug "double free or corruption" happens with OpenMP

### ISSUE THREAD

**Issue by PeizeLin** [abacusmodeling/abacus-develop#155]
## Describe the Bug
In this case, bug "double free or corruption" can be reproduced.
The bug may be in `Gint_Gamma::gamma_vlocal()`;

## To Reproduce
When running in some of the nodes with OMP_NUM_THREADS >= 24, this bug may happen.
`mpirun -n 1 -env OMP_NUM_THREADS=24 ABACUS.mpi`
Running in other nodes works successfully.

## Environment
- OS: CentOS Linux release 7.4.1708
- Compiler: mpiicpc 19.0.3.199

## test case
[Zn3.zip](https://github.com/abacusmodeling/abacus-develop/files/8925834/Zn3.zip)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
