### ISSUE TITLE
The ground-state energy decreases after structural relaxation

### ISSUE THREAD

**Issue by lzcun** [abacusmodeling/abacus-develop#156]
I recently did 100 fs AIMD at 400K and optimized the geometry. I found the ground-state energy decreases after structural relaxation. The following is the FINAL_ETOT obtained calculating the SCF before and after  the relaxation:
The SCF before relaxing:
![image](https://user-images.githubusercontent.com/82214631/174479965-f2f59849-a7a1-4a33-8a2e-9888de7a314f.png)

The SCF after relaxing:
![image](https://user-images.githubusercontent.com/82214631/174479785-866a9eb1-7cb0-4fbd-b073-74118a5168dc.png)

I wonder whether it is a bug of ABACUS. And the basis_type all I used is 'lcao'.

**Comment by YuLiu98** [comment]
Hi, can you provide related input and output files?

**Comment by lzcun** [comment]
OK, it has INPUT, STRU, and runing_scf.log about before and after relaxation.  In doc 'relax' are the INPUT and output files.

[relax_scf.zip](https://github.com/abacusmodeling/abacus-develop/files/8937849/relax_scf.zip)

**Comment by YuLiu98** [comment]
The width of Gaussian smearing is 0.2 Ry in the structural relaxation, while that is 0.02 Ry in the SCF, which causes the opposite results.

In the structural relaxation, the initial energy is **-12644.7096725** eV, and the final energy is **-12649.07110999118** eV.
In the SCF, the initial energy is **-12634.6964808355114656** eV, and the final energy is **-12630.7770245020055881** eV.

And I notice that the max force of the relaxed STRU is > 0.01 eV/A if `smearing_sigma` = 0.02 Ry, showing that the parameters between relax and scf must be consistent to obtain the correct result.

**Comment by lzcun** [comment]
Thanks for your reply! Sorry, I did not notice that before. Now the results are right when the parameters become consistent.
