### ISSUE TITLE
Failed to calculate band structure using nscf calculation with ABACUS v2.3.0

### ISSUE THREAD

**Issue by mzjb** [abacusmodeling/abacus-develop#159]
## Describe the Bug
I use ABACUS to perform `scf` and `nscf` calculation with `HSE` functional to calculate the band structure of GeS. During the `nscf` calculation, I got an error:
```
 *********************************************************
 *                                                       *
 *                  WELCOME TO ABACUS                    *
 *                                                       *
 *            'Atomic-orbital Based Ab-initio            *
 *                  Computation at UStc'                 *
 *                                                       *
 *          Website: http://abacus.ustc.edu.cn/          *
 *                                                       *
 *********************************************************
 Sat Jul  2 21:23:44 2022
 MAKE THE DIR         : OUT.ABACUS/
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
In Pseudopot_upf::read_pseudo_header : dft_functional from INPUT does not match that in pseudopot file
Please make sure this is what you need
 dft_functional readin is: hse
 dft_functional in pseudopot file is: PBE
In Pseudopot_upf::read_pseudo_header : dft_functional from INPUT does not match that in pseudopot file
Please make sure this is what you need
 UNIFORM GRID DIM     : 32 * 32 * 250
 UNIFORM GRID DIM(BIG): 16 * 16 * 125
 DONE(0.752866   SEC) : SETUP UNITCELL
 DONE(0.757325   SEC) : INIT K-POINTS
 ---------------------------------------------------------
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       61              2           26          
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 B       2s2p1d-8au      13          1           
 N       2s2p1d-6au      13          1           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 DONE(0.783077   SEC) : INIT PLANEWAVE
 DONE(0.813701   SEC) : INIT CHARGE
 START POTENTIAL      : file
 DONE(1.10344    SEC) : INIT POTENTIAL
 -------------------------------------------
 NONSELF-CONSISTENT : 
 -------------------------------------------
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 2654 RUNNING AT node2.cluster
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================
```

## To Reproduce
1. Download the code from https://github.com/abacusmodeling/abacus-develop/archive/refs/tags/v2.3.0.tar.gz
2. Build ABACUS with intel oneapi MKL 2022.0.2 + MPI 2021.5.1
3. Run `scf` calculation using ABACUS with the input file `INPUT.scf`, `KPT.scf` and `STRU` from [hse_nscf.zip](https://github.com/abacusmodeling/abacus-develop/files/9063761/hse_nscf.zip)
4. Run `nscf` calculation using ABACUS with the input file `INPUT.nscf`, `KPT.nscf` and `STRU` from [hse_nscf.zip](https://github.com/abacusmodeling/abacus-develop/files/9063761/hse_nscf.zip), and get an error

## Environment
- openSUSE Leap 15.3
- icpc version 2021.5.0 (gcc version 7.5.0 compatibility)
- Intel oneapi MKL 2022.0.2, MPI 2021.5.1

## Additional Context
- I can get the correct result with the same input file using an older version of ABACUS (2021.5 from Github)
- I can get the correct result if the `xc` is set to `PBE` rather than `HSE` using ABACUS v2.3.0

**Comment by dyzheng** [comment]
Thanks for your report, when HSE is choosed and nscf calculation in ABACUS would read HR_exx_$rank rather than read in charge and DM and recalculate the H_exx again. 
But there is something wrong in this code now, which is okay in the past, we will try to fix that.

**Comment by dyzheng** [comment]
https://github.com/deepmodeling/abacus-develop/pull/1050 The problem has been fixed in this PR, you can try ABACUSv2.3.1 version after tomorrow.
