### ISSUE TITLE
Failed to output H(R) and S(R) using HSE functional

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#162]
## Bug description
When I set `out_mat_hs2    1` and  `out_mat_r    1` with `dft_functional    hse`  in INPUT,  an error reported as follows:
```
ABACUS.mpi: ./module_orbital/ORB_atomic_lm.cpp:181: void Numerical_Orbital_Lm::copy_parameter(const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> &, const int &, const int &, const int &, const int &, const double *, const double *, const int &, const double &, const double &): Assertion `nk_in<10000' failed.
```
Then I comment out this line, the  H(R) and S(R) matrices can be output successfully. So can this assertion be deleted in the future?

## Version
The latest development version of ABACUS in 2022/7/11

**Comment by dyzheng** [comment]
Did this problem still exist?@1041176461

**Comment by 1041176461** [comment]
> Did this problem still exist?@1041176461

In my new PR, I delete assertion `nk_in<10000`, and it will output HR successfully using HSE
