### ISSUE TITLE
ABACUS v2.3.0 no longer outputs orbital definitions for H(R) like older versions of ABACUS

### ISSUE THREAD

**Issue by mzjb** [abacusmodeling/abacus-develop#163]
## Describe the Bug
I want to get the Kohn-Sham matrix element in real space H(R) by ABACUS, and I need to figure out which orbtial each line of H(R) corresponds to. 

In the past, I used an old version of ABACUS. If I set `out_hs2  1`, I could get an output file in `OUT.ABACUS/Orbital` recording the orbtial definition. However, when I switch to the new version of v2.3.0 and set `out_mat_hs2  1`, the file `OUT.ABACUS/Orbital` no longer appears after the `scf` calculation is complete.

Maybe this is because `out_hs2` was renamed `out_mat_hs2`.

## To Reproduce
1. Download the code from https://github.com/abacusmodeling/abacus-develop/archive/refs/tags/v2.3.0.tar.gz
2. Build ABACUS with intel oneapi MKL 2022.0.2 + MPI 2021.5.1
3. Run `scf` calculation using ABACUS with the input file from [BN.zip](https://github.com/abacusmodeling/abacus-develop/files/9118407/BN.zip)
4. There is no file `Orbital` in `OUT.ABACUS/`
5. If I use an older version of ABAUCS to perform the calculate for the above flow, I can get a file `OUT.ABACUS/Orbital` like:
    ```
     io    spec    l    m    z  sym
      0       B    0    0    1    s          
      0       B    0    0    2    s          
      0       B    1    0    1    px         
      0       B    1    1    1    py         
      0       B    1    2    1    pz         
      0       B    1    0    2    px         
      0       B    1    1    2    py         
      0       B    1    2    2    pz         
      0       B    2    0    1    d3z^2-r^2  
      0       B    2    1    1    dxy        
      0       B    2    2    1    dxz        
      0       B    2    3    1    dx^2-y^2   
      0       B    2    4    1    dyz        
      1       N    0    0    1    s          
      1       N    0    0    2    s          
      1       N    1    0    1    px         
      1       N    1    1    1    py         
      1       N    1    2    1    pz         
      1       N    1    0    2    px         
      1       N    1    1    2    py         
      1       N    1    2    2    pz         
      1       N    2    0    1    d3z^2-r^2  
      1       N    2    1    1    dxy        
      1       N    2    2    1    dxz        
      1       N    2    3    1    dx^2-y^2   
      1       N    2    4    1    dyz        
  
  
     io =Orbital index in supercell
   spec =Atomic species label
      l =Angular mumentum quantum number
      m =Magnetic quantum number
      z =Zeta index of orbital
    sym =Symmetry name of real orbital
    ```

## Environment
- openSUSE Leap 15.3
- icpc version 2021.5.0 (gcc version 7.5.0 compatibility)
- Intel oneapi MKL 2022.0.2, MPI 2021.5.1

**Comment by mzjb** [comment]
I found that if `out_dos  1` is set, then I can get the file `OUT.ABACUS/Orbital`. But I think users may also need `OUT.ABACUS/Orbital` when they want to output H(R) and don't want to output DOS.

**Comment by dyzheng** [comment]
Can you try input parameter “out_element_info 1” in INPUT file?

**Comment by Fadelis98** [comment]
> I found that if `out_dos 1` is set, then I can get the file `OUT.ABACUS/Orbital`. But I think users may also need `OUT.ABACUS/Orbital` when they want to output H(R) and don't want to output DOS.

Same issue here, I think the orbital information is necessary when people want to use H(R). so the information is expected to be saved when `out_mat_hs2=1`

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
