### ISSUE TITLE
V.2.3.1 run MD, when I use bx/by/bz the program will stop 

### ISSUE THREAD

**Issue by lzcun** [abacusmodeling/abacus-develop#168]
I am running MD simulations with V.2.3.1,  I want to add bx/by/bz parameters to optimize performance.  But if I add bx/by/bz, the program would stop at the beginning (see the below), with the cores I used were 6/8/12。

**Comment by lzcun** [comment]
![微信图片_20220720174148](https://user-images.githubusercontent.com/82214631/179951349-6a0f3e18-1141-4426-8a84-b57c3ddae45b.png)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
