### ISSUE TITLE
There is an error when use ABACUS to do HSE+SOC calculation

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#173]
### Describe the bug

When I use ABACUS (version: cb47661efa1ff81ed8d2e47c606978f646b24b7c) to do HSE+SOC, there is an error reported as follows:
```
WARNING: Total thread number on this node mismatches with hardware availability. This may cause poor performance.
Info: Local MPI proc number: 3,OpenMP thread number: 9,Total thread number: 27,Local thread limit: 28
ABACUS.mpi: ./module_base/complexmatrix.cpp:145: ModuleBase::ComplexMatrix ModuleBase::operator+(const ModuleBase::ComplexMatrix &, const ModuleBase::ComplexMatrix &): Assertion `m1.nr == m2.nr' failed.
ABACUS.mpi: ./module_base/complexmatrix.cpp:145: ModuleBase::ComplexMatrix ModuleBase::operator+(const ModuleBase::ComplexMatrix &, const ModuleBase::ComplexMatrix &): Assertion `m1.nr == m2.nr' failed.
ABACUS.mpi: ./module_base/complexmatrix.cpp:145: ModuleBase::ComplexMatrix ModuleBase::operator+(const ModuleBase::ComplexMatrix &, const ModuleBase::ComplexMatrix &): Assertion `m1.nr == m2.nr' failed.
````
Here are my input and output files:
[hse-soc.zip](https://github.com/abacusmodeling/abacus-develop/files/9220094/hse-soc.zip)

I also try to use charge files output by the old version from last year to do HSE+SOC band structure calculation with new version, and there is also a wrong band structure obtained. Here, I upload the old and new `BANDS_1.dat` files:
[bands.zip](https://github.com/abacusmodeling/abacus-develop/files/9226558/bands.zip)

However, a correct band structure obtained when I use new version to do standard HSE band structure calculation based on old charge files. So I think there may be some errors in HSE+SOC codes of new version.

**Comment by 1041176461** [comment]
I also used ABACUS with external library `LIBRI` to do HSE+SOC calculation, the above error was not reported. However, the calculation can not converge in HSE loop:
![image](https://user-images.githubusercontent.com/40336950/193180125-b99997a4-6c3f-4385-b0af-8f6d1de6b789.png)
and end with exceptions: 
![image](https://user-images.githubusercontent.com/40336950/193180063-71a6cbe1-4aae-4454-a07e-afe4597995ea.png)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
