### ISSUE TITLE
Bad results of V-E curves for Fe LCAO/PW calculations

### ISSUE THREAD

**Issue by wszhang** [abacusmodeling/abacus-develop#187]
### Describe the bug

Compared with ABACUS v2.0, ABACUS v2.2.2 gives wrong VE results (should also exist in later versions), shown as the follows:

![bad VE abacus v2 2 2 compared with v2 0](https://user-images.githubusercontent.com/10769183/189663061-5a12e039-fb5b-4863-afdd-c86b232912f4.png)
Left: ABACUS v2.0 results,      Right: ABAUCS v2.2.2 results.

The data for above plotting: 
[Fe_gga_10au_100Ry_TZDP_VE0.94_lcao.zip](https://github.com/abacusmodeling/abacus-develop/files/9548280/Fe_gga_10au_100Ry_TZDP_VE0.94_lcao.zip)

### To Reproduce

Here is the input files for calculation:
[inputs.zip](https://github.com/abacusmodeling/abacus-develop/files/9548188/inputs.zip)

### Environment

For ABACUS v2.0:
module load elpa/2016.05.004/intel-2018.update4 intel/2018.update4 intelmpi/2018.update4 mkl/2018.update4

For ABACUS v2.2.2:
module load gcc/9.2.0 elpa/2021.05.002/intelmpi2018 intelmpi/2018.update4

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
