### ISSUE TITLE
Different converged PW energe for Se dimer structure by using v2.3.0 and v2.0.0

### ISSUE THREAD

**Issue by wszhang** [abacusmodeling/abacus-develop#199]
### Describe the bug

ABACUS v2.3.0 and 2.0.0 produced different converged PW energes for Se dimer structure.

for v2.0.0:
 charge density convergence is achieved
 final etot is -512.815324635547 eV

 STATE ENERGY(eV) AND OCCUPATIONS. 1/1 kpoint (Cartesian) = 0.00000 0.00000 0.00000 (13507 pws)
 [spin1_state]        1     -20.934722       2.000000
 [spin1_state]        2     -14.542070       2.000000
 [spin1_state]        3      -8.612504       2.000000
 [spin1_state]        4      -8.211223       2.000000
 [spin1_state]        5      -8.211148       2.000000
 [spin1_state]        6      -4.085818       1.000268
 [spin1_state]        7      -4.085753       0.999732
 [spin1_state]        8      -3.489782       0.000000
 [spin1_state]        9      -1.978077       0.000000
 [spin1_state]       10      -1.977633       0.000000

for 2.3.0:
 charge density convergence is achieved
 final etot is -513.726514779 eV

 STATE ENERGY(eV) AND OCCUPATIONS    NSPIN == 1
 1/1 kpoint (Cartesian) = 0 0 0 (13506 pws)
       1       -18.7319        2.00000
       2       -12.8708        2.00000
       3       -7.20274        2.00000
       4       -7.20257        2.00000
       5       -6.95123        2.00000
       6       -3.32170        1.28991
       7       -3.19708       0.355689
       8       -3.19684       0.354400
       9      -0.284140        0.00000
      10       0.369519        0.00000

### To Reproduce

The input fils and output files:
[spin1_abacus-pw_2.0vs3.0.zip](https://github.com/abacusmodeling/abacus-develop/files/9657652/spin1_abacus-pw_2.0vs3.0.zip)

### Environment

The following modulefiles were used in Hanhai20@USTC:

for abacus 2.0.0:
module		 load intel/2018.update4 intelmpi/2018.update4 mkl/2018.update4 
module		 load /opt/Modules/lib/elpa/2016.05.004/intel-2018.update4

for abacus 3.0.0:
module		 load intel/2019.update5 intelmpi/2019.update5 mkl/2019.update5 gcc/9.2.0 elpa/2021.05.002/intelmpi2018

**Comment by dyzheng** [comment]
I have retest Se-dimer with 1.9 distance and find that `ks_solver cg` lead to -513.726514779eV and `ks_solver dav` lead to -512.815324635547eV.
Note: I used `nbands 20` for enhance robust of diagonalization. 

(Screen output)
```
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 DA1    -5.129074e+02  0.000000e+00   5.686e-01  1.708e+01  
 DA2    -5.132766e+02  -3.692763e-01  2.566e-01  2.247e+00  
 DA3    -5.092154e+02  4.061274e+00   2.380e+00  4.831e+00  
 DA4    -5.126262e+02  -3.410865e+00  1.612e-01  2.568e+00  
 DA5    -5.125761e+02  5.009499e-02   1.215e-01  1.975e+00  
 DA6    -5.127251e+02  -1.489932e-01  8.579e-04  2.138e+00  
 DA7    -5.127622e+02  -3.704226e-02  2.215e-03  7.909e+00  
 DA8    -5.128021e+02  -3.994833e-02  1.974e-03  1.972e+00  
 DA9    -5.128077e+02  -5.573774e-03  3.679e-04  3.873e+00  
 DA10   -5.128100e+02  -2.264354e-03  3.571e-04  2.283e+00  
 DA11   -5.128064e+02  3.555817e-03   1.578e-04  2.496e+00  
 DA12   -5.128107e+02  -4.335449e-03  1.389e-04  3.007e+00  
 DA13   -5.128129e+02  -2.146815e-03  6.801e-05  5.311e+00  
 DA14   -5.128147e+02  -1.833987e-03  1.673e-05  3.140e+00  
 DA15   -5.128154e+02  -6.958200e-04  4.094e-06  3.230e+00  
 DA16   -5.128154e+02  -3.001393e-05  6.727e-07  2.666e+00  
 DA17   -5.128155e+02  -1.552457e-05  4.030e-07  3.420e+00  
 DA18   -5.128155e+02  -2.462081e-06  1.362e-07  2.817e+00  
 DA19   -5.128155e+02  -1.326276e-06  1.358e-08  2.618e+00
```
(Total energy and band energys)
```
STATE ENERGY(eV) AND OCCUPATIONS    NSPIN == 1
 1/1 kpoint (Cartesian) = 0 0 0 (33761 pws)
       1       -20.9341        2.00000
       2       -14.5414        2.00000
       3       -8.61194        2.00000
       4       -8.21075        2.00000
       5       -8.21070        2.00000
       6       -4.08544        1.00005
       7       -4.08543       0.999946
       8       -3.49056    6.27934e-10
       9       -1.97658        0.00000
      10       -1.97655        0.00000
      11       -1.56123        0.00000
      12       -1.56121        0.00000
      13       -1.53215        0.00000
      14       -1.53212        0.00000
      15       -1.31344        0.00000
      16       -1.31343        0.00000
      17      -0.302143        0.00000
      18     -0.0417651        0.00000
      19      0.0526112        0.00000
      20       0.883383        0.00000

 --------------------------------------------
 !FINAL_ETOT_IS -512.8154568691700 eV
 --------------------------------------------
```

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
