### ISSUE TITLE
There is no `.cube` file output with `out_chg=1`

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#204]
### Describe the bug

Iwant to plot charge using Vesta. So I used version in `develop`  branch, with the following input parameters:
![4bc1ea039871d2cb1fd01a83ae21679](https://user-images.githubusercontent.com/40336950/193046182-1621c691-a648-4265-84b3-4044f39798fa.jpg)
to output charge. There is no `.cube` file output, though I set `out_chg=1`.
Here is my `OUT.ABACUS` directory:
![image](https://user-images.githubusercontent.com/40336950/193047916-174b6daa-8c75-4a0c-80a9-c7094e885814.png)

### Expected behavior

A charge file in `.cube` format can be obtained from ABACUS

### To Reproduce

run ABACUS with `out_chg=1`

**Comment by dyzheng** [comment]
https://github.com/deepmodeling/abacus-develop/pull/1310 This PR has been merged into abacusmodeling/abacus-develop/develop , can it help your problem?@1041176461

**Comment by 1041176461** [comment]
> [deepmodeling#1310](https://github.com/deepmodeling/abacus-develop/pull/1310) This PR has been merged into abacusmodeling/abacus-develop/develop , can it help your problem?@1041176461

I used version 1c0dee8cc878b9b6488c26407bffca6c2fa8ff6a to test again, however, it still doesn't work.

**Comment by 1041176461** [comment]
> [deepmodeling#1310](https://github.com/deepmodeling/abacus-develop/pull/1310) This PR has been merged into abacusmodeling/abacus-develop/develop , can it help your problem?@1041176461

I used the newest version in `develop` branch to test and it did work!
