### ISSUE TITLE
File already exists but no hash specified (use URL_HASH)

### ISSUE THREAD

**Issue by syllzp** [abacusmodeling/abacus-develop#210]
### Details

When installed Abacus 3.0.0 offline, I download https://github.com/USCiLab/cereal/archive/refs/tags/v1.3.0.tar.gz and put it in abacus-develop-3.0.0/build/_deps/cereal-subbuild/cereal-populate-prefix/src/v1.3.0.tar.gz. And reported -- File already exists but no hash specified (use URL_HASH):
  file='/public/software/abinitio/Abacus/abacus-develop-3.0.0/build/_deps/cereal-subbuild/cereal-populate-prefix/src/v1.3.0.tar.gz'
Old file will be removed and new file downloaded from URL.
How to solve this offline install issue

**Comment by caic99** [comment]
Hi @syllzp ,
Please install cereal in another path and use `-DCEREAL_INCLUDE_DIR=xxx` with cmake. See http://abacus.deepmodeling.com/en/latest/quick_start/easy_install.html.

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
