### ISSUE TITLE
MD calculation is failed using ABACUS in develop branch

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#221]
### Describe the bug

@HeFuxiang94 and I do MD calculation using ABACUS in develop branch, but there is a bug reported as follows:

![image](https://user-images.githubusercontent.com/40336950/197325753-b825737e-b0d6-4834-aa52-274f11f4b2f1.png)

We test two examples (H2 and CO), the calculations are both ended unexpectedly after the initial MD step.

Here are the input and output files:
[bug_MD_test.zip](https://github.com/abacusmodeling/abacus-develop/files/9843767/bug_MD_test.zip)

**Comment by dyzheng** [comment]
This error come from https://github.com/deepmodeling/abacus-develop/pull/1406 
@YuLiu98 can you help for this problem?
