### ISSUE TITLE
Bad results of band structure for SCAN calculations

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#223]
### Describe the bug

I use SCAN functional to output band structure of CsAgInCl, but its result (left) is quite different from HSE (right):
![image](https://user-images.githubusercontent.com/40336950/199151838-7eab5836-d2f6-4603-acc2-1873ab4ca481.png)
especially there is a large gap in valence bands which is incorrect.

Here are my input and output files:
[Uploading test.zip…]()

### Expected behavior

I have compared PBE and HSE band structures, the dispersion is similar, except for the band gaps. Thus, we can expect that the same conclusion can be obtained by using SCAN.

**Comment by wenfei-li** [comment]
I'm wondering if all the parameters are converged?

**Comment by wenfei-li** [comment]
I cannot download the files.

**Comment by 1041176461** [comment]
@wenfei-li @dyzheng I use SCAN in PWscf to calculate band structure and find that it seems like more reasonable than ABACUS results.

![image](https://user-images.githubusercontent.com/40336950/200271977-9103d297-3443-49a0-b3f8-1af4e656150e.png)

I also use SCAN in two codes to fit bond length (d) and here are Etot-d curves

![image](https://user-images.githubusercontent.com/40336950/200272894-f7ce6401-c9ba-48de-b821-5ceba6235c2b.png)

and (Etot-Emin)-d curves which are almost coincide:

![image](https://user-images.githubusercontent.com/40336950/200272991-aa8920de-7221-4ecd-9d6f-18af48fc8998.png)

So I guess there may be something wrong in NSCF calculation using ABACUS.

Here are my PWscf input files:
[espresso.zip](https://github.com/abacusmodeling/abacus-develop/files/9949937/espresso.zip)

**Comment by wenfei-li** [comment]
Oh i get it now, it has to do with nscf. In current nscf we only read the density, and kinetic energy density (which is required by meta-GGA) is initialized from scartch.
The solution would be to output kinetic energy density and read it in for nscf calculations.
We are currently doing a refactor of the ElecState class which governs initialization of charge and so on, will address this issue in the process.

**Comment by 1041176461** [comment]
I plot band structure based on HR matrix, it seems correct.
![scan](https://user-images.githubusercontent.com/40336950/200561237-e80bc541-7e89-4fdf-9006-8459a0a690e2.png)

There is an another interesting question. I find that there is an extra flat band at around 8.0 eV in QE band structure, regardless of what functionals are used, e.g. PBE, SCAN and HSE. And in ABACUS PW calculation, this flat band also appears. 
![pw](https://user-images.githubusercontent.com/40336950/200562727-acf778cf-bdf0-4e3d-b2c8-1cb593eb4163.png)

However, in ABACUS-LCAO, VASP and some articles, it does't exist.
- ABACUS-LCAO
![lcao](https://user-images.githubusercontent.com/40336950/200562834-721683f0-ba0a-4494-9948-f0ebc6f4477b.png)

- VASP
![pbe](https://user-images.githubusercontent.com/40336950/200562924-16fde2b2-d933-4e61-87ab-4a1fa483dc65.jpg)

- [J. Phys. Chem. Lett. 2017, 8, 4, 772–778](https://pubs.acs.org/doi/10.1021/acs.jpclett.6b02682)
![article](https://user-images.githubusercontent.com/40336950/200563027-2e8e8a2a-7050-4e40-92a5-520504a856d3.png)

**Comment by 1041176461** [comment]
I find that the flat band only exists when ONCV pseudo-potential is used, if I use Dojo pseudo-potential, the band structure is reasonable. Here is band structure obtained from PBE with Dojo, using QE:

![dojo-pbe](https://user-images.githubusercontent.com/40336950/201251403-aa6682d3-93d7-423a-9560-2914f52a393e.png)

**Comment by wenfei-li** [comment]
Good to know!
