### ISSUE TITLE
Program exits abnormally

### ISSUE THREAD

**Issue by zjdai** [abacusmodeling/abacus-develop#224]
### Describe the bug

- Program exits abnormally with mpi error in scf calculation 
- Charge density output is normal
- H,S matrix output is normal
- ABACUS version is 3.0.1

### To Reproduce

[Fe.tar.gz](https://github.com/abacusmodeling/abacus-develop/files/9915168/Fe.tar.gz)

**Comment by dyzheng** [comment]
"cal_force" and "cal_stress" is not supported with SOC
