### ISSUE TITLE
PBEsol+SOC cannot converge

### ISSUE THREAD

**Issue by 1041176461** [abacusmodeling/abacus-develop#231]
### Describe the bug

I use PBEsol+SOC to do SCF calculation for CsAgBiBr, but iterations cannot converge within 100 electric steps.
Here are my input files:
[input.zip](https://github.com/abacusmodeling/abacus-develop/files/10037410/input.zip)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
