### ISSUE TITLE
SCF calculation do not converge with L(S)DA+U in nspin=2 system

### ISSUE THREAD

**Issue by zjdai** [abacusmodeling/abacus-develop#236]
### Describe the bug

- abacus version abacus-develop-3.0.3
- nspin=2 system without soc (MnSbTe system)
- wrong with local occupation matrices in LDA+U
- correct with old abacus version (abacus-develop-master_2.2.0) 

### To Reproduce

[MnSbTe.zip](https://github.com/abacusmodeling/abacus-develop/files/10098220/MnSbTe.zip)

**Comment by zjdai** [comment]
[MnSbTe_old version.zip](https://github.com/abacusmodeling/abacus-develop/files/10098237/MnSbTe_old.version.zip)

**Comment by dyzheng** [comment]
@wenfei-li There is a funny case related with plus-U, same input leads to different SCF performance between ABACUSv2.2.0 and ABACUSv3.0.3. I will retest this case to find out what is this difference from, nspin2 or DFTU.

**Comment by dyzheng** [comment]
> MnSbTe_old version.zip

Your "mixing_beta" setting is 0.4 in the v3.0.3 test case, but is 0.1 in this case.

Can you use same parameters to test different version?@zjdai

**Comment by dyzheng** [comment]
Another problem is the pseudopotential and orbital files you used is from DOJO library, you should put them in your test case package.@zjdai
