### ISSUE TITLE
cell-relax do not converge with L(S)DA+U in spin=2 system

### ISSUE THREAD

**Issue by zjdai** [abacusmodeling/abacus-develop#237]
### Describe the bug

- comparison tests of cell-relax calculation in MnSbTe system

- nspin=2 without  L(S)DA+U  in ABACUS version abacus-develop-3.0.3 
-  converge with force and stress
- test file MnSbTe_1.zip

-  nspin=2 with  L(S)DA+U  in ABACUS version abacus-2022-9-30-3.0.0
- converge with force in every step with lattice vector constrained while stress do not converge
- test file MnSbTe_2.zip

### To Reproduce

[MnSbTe_1.zip](https://github.com/abacusmodeling/abacus-develop/files/10109073/MnSbTe_1.zip)

[https://www.jianguoyun.com/p/DXx0D9QQ7fzGCBjTuekEIAA ](url)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
