### ISSUE TITLE
Incorrect total enery output when using tddft 

### ISSUE THREAD

**Issue by ESROAMER** [abacusmodeling/abacus-develop#244]
### Describe the bug

The oscillation of the total enery read from running_md.log is too large to be normal. I found this problem when doing a ground state tddft calculation of H2 molecular. 

### Expected behavior

Without excitation, the tddft calculation should have simliar result with md calculation. So I compare their result using the same STRU and INPUT file (except keyword "tddft").
![2](https://user-images.githubusercontent.com/104255052/206371710-e5f4af8b-6749-460c-ac22-657b1758497d.png)
![1](https://user-images.githubusercontent.com/104255052/206371718-9b1f1b3c-bb79-4597-a7aa-90f186ee16dc.png)
Although they are close when calculating bond length oscilation, the total energy oscilation in tddft is much more larger than which in md. The result in md are more reliable cause the NVE ensemble (md_type = 0) was used.

### To Reproduce

Input file of these two.
[INPUT.zip](https://github.com/abacusmodeling/abacus-develop/files/10182683/INPUT.zip)

**Comment by dyzheng** [comment]
Please upload your screen output with your input files.

**Comment by dyzheng** [comment]
The problem is total energy(grep "Energy     " in running_md.log) in MD is increasing with TDDFT.
![image](https://user-images.githubusercontent.com/49852742/206381193-8a2cd3c7-b132-4093-9224-fa27ae9f93f8.png)

@lyb9812 please check that.

**Comment by ESROAMER** [comment]
The version used in the test was v3.0.0, and the problem still exist in v3.0.2. The latest version has not been tested yet.

**Comment by ESROAMER** [comment]
A more detail input and result files.
[Test_data.zip](https://github.com/abacusmodeling/abacus-develop/files/10182977/Test_data.zip)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
