### ISSUE TITLE
 word = relax_new  Fail to read parameters. 

### ISSUE THREAD

**Issue by jinxin68** [abacusmodeling/abacus-develop#245]
### Describe the bug

I want to use the bfgs algorithm to relax structure and have to set "relax_new = false", but abacus can't read the paramter.
![image](https://user-images.githubusercontent.com/102202772/207284923-18d47e62-5897-4038-a754-d76a7c2cd30d.png)
![image](https://user-images.githubusercontent.com/102202772/207284993-d7ef562d-60cb-4c30-a8c5-3aef5ac64add.png)
![image](https://user-images.githubusercontent.com/102202772/207285305-a2882b7b-e6d2-460a-81ca-262607da10ba.png)

**Comment by jinxin68** [comment]
My abacus version is v3.0.4

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
