### ISSUE TITLE
The calculation is not convergent for two-dimensional materials

### ISSUE THREAD

**Issue by jinxin68** [abacusmodeling/abacus-develop#246]
### Details

[mos2.zip](https://github.com/abacusmodeling/abacus-develop/files/10235264/mos2.zip)

**Comment by dyzheng** [comment]
I have transfered this issue to https://github.com/deepmodeling/abacus-develop/issues/2063

**Comment by dyzheng** [comment]
It caused by force result would has large error when SCF threshold is large.
Please try 
```
force_thr_ev		1.0e-2
scf_thr                      1e-7
```
