### ISSUE TITLE
"envelope" feature has been broken

### ISSUE THREAD

**Issue by dyzheng** [abacusmodeling/abacus-develop#248]
### Describe the bug

In examples/wfc/lcao_ienvelope_Si2/ case, there would be failure with "bash run.sh".

**Comment by dyzheng** [comment]
![img_v2_de2e4cf7-7cb5-48a3-bd5b-a6f15a07bc8g](https://user-images.githubusercontent.com/49852742/208674694-b8e7af11-0c1f-4e9e-990d-64a75e01350c.jpg)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
