### ISSUE TITLE
Convergence of self-consistent computation of the slab model of TaAs

### ISSUE THREAD

**Issue by xinliang-huang** [abacusmodeling/abacus-develop#254]
### Details

[scf_TaAs-slab.zip](https://github.com/abacusmodeling/abacus-develop/files/10802377/scf_TaAs-slab.zip)

The mixing parameter of my slab model will have a trend of convergence only when it is 0.01, and will fluctuate between e-04 and e-05 in the future, even if the mixing parameter is lower than 0.01.  I don't know why.

Setting "scf_thr 1.0e-4" can converge, and I have calculated the band, and the result should be correct. The following is my band without considering SOC (left figure). I think that considering SOC should be consistent with the literature (right figure, literature: Lv B Q, Weng H M, Fu B B, et al. Experimental discovery of Weyl semimetal TaAs[J]. Physical Review X, 2015, 5(3): 031013. )!

![band](https://user-images.githubusercontent.com/122172190/220590528-6e99aef5-9d49-4346-8146-aabba9c4b601.png)

**Comment by dyzheng** [comment]
I have transfer this issue to https://github.com/deepmodeling/abacus-develop/issues/2062 .

**Comment by dyzheng** [comment]
This setting can work:
```
smearing_method     mp
smearing_sigma      0.02

mixing_beta         0.1
mixing_gg0          1.5
mixing_ndim         20
```
