### ISSUE TITLE
Something wrong when installing ABACUS.

### ISSUE THREAD

**Issue by tangerious** [abacusmodeling/abacus-develop#255]
### Details

We encountered the following issue when installing ABACUS according to the online documentation：

- `sudo apt update && sudo apt install -y libopenblas-openmp-dev liblapack-dev libscalapack-mpi-dev libelpa-dev libfftw3-dev libcereal-dev libxc-dev g++ make cmake bc git`.  
We used yum instead of apt because our system is Centos, The following message appeared , I am not sure if this will affect the installation later.![1](https://user-images.githubusercontent.com/117794432/221161713-ace79018-c8ee-48cd-b57a-1bc0843e590e.png)
- Then we used `wget l_BaseKit_p_2021.4.0.3422_offline.sh`, `sudo bash l_BaseKit_p_2021.4.0.3422_offline.sh`, `wget l_HPCKit_p_2021.4.0.3347_offline.sh`, `sudo bash l_HPCKit_p_2021.4.0.3347_offline.sh` to install the whole Toolkit. For gcc compiler, we used the configure command :`../configure CFLAGS="-O3 -march=native -funsafe-loop-optimizations -funsafe-math-optimizations -ftree-vect-loop-version -ftree-vectorize" \ FCFLAGS="-O2 -mavx" --disable-avx512 `. The following message appeared:![2](https://user-images.githubusercontent.com/117794432/221164329-dab657b5-9df5-4da0-b1f6-0caa6359d9c8.png)
- Finally we used Intel oneAPI: `CC=mpiicc CXX=mpiicpc FC=mpiifort ../configure FCFLAGS="-mkl=cluster"`, and we got:![3](https://user-images.githubusercontent.com/117794432/221165233-ab2ff2a8-2c00-417b-9f1a-fac85737cfae.png)

then we make it, but we got another error again:
![4](https://user-images.githubusercontent.com/117794432/221167293-28b75e4e-5ba7-409d-9cb7-17b096f86c46.png)
**We have no idea about this, and came here to ask for everyone's advice.**

**Comment by dyzheng** [comment]
I have transfer this issue to https://github.com/deepmodeling/abacus-develop/issues/2061 .
