### ISSUE TITLE
Which compiler is recommended for the GPU version?

### ISSUE THREAD

**Issue by pplab** [abacusmodeling/abacus-develop#263]
### Details

Hi all,

I want to test the GPU version on a workstation with a 2080Ti card. I have two compiler suites: 1) intel one api+cuda11.5 and 2) nvhpc 21.9. Which is better?

Thanks for any suggestions.

**Comment by dyzheng** [comment]
@denghuilu can you help for this question?

**Comment by denghuilu** [comment]
I believe that the CPU compiler is not particularly sensitive to the GPU implementation, which means that you should be able to compile ABACUS using either compiler without encountering any issues. However, as we have not tested ABACUS-GPU with the NVIDIA HPC compiler yet, we would appreciate it if you could test it and provide us with some feedback.

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
