### ISSUE TITLE
the abnormal total-stress values in Mn3ZnC system 

### ISSUE THREAD

**Issue by zjdai** [abacusmodeling/abacus-develop#266]
### Describe the bug

- calculating cell-relax for Mn3ZnC bulk system
- abacus version  is abacus_developer-v3.1.4
- The anomalous total stress values can also be observed in both abacus_developer-v3.1.2 and abacus_developer-v3.1.3, regardless of whether the LDA+U feature is enabled or not

### To Reproduce

[MnZnC-cell_relax.zip](https://github.com/abacusmodeling/abacus-develop/files/10986086/MnZnC-cell_relax.zip)

**Comment by dyzheng** [comment]
It has transferred to https://github.com/deepmodeling/abacus-develop/issues/2169
