### ISSUE TITLE
When compiling ABACUS with Cmake, configure passed, but an elpa_eigenvectors_all_host_arrays_d undefined  error occurred during the make build phase.

### ISSUE THREAD

**Issue by A-006** [abacusmodeling/abacus-develop#271]
### Describe the bug

when i compile the ABACUS with Cmake,i installed the epla on Ubuntu 22.04 like this

> sudo apt update && sudo apt install -y libopenblas-openmp-dev liblapack-dev libscalapack-mpi-dev libelpa-dev libfftw3-dev libcereal-dev libxc-dev g++ make cmake bc git
During the Configure phase of the installation process in EPLA,this is gotten
![屏幕截图 2023-04-16 230621](https://user-images.githubusercontent.com/74701833/232322033-eb931702-a792-4151-af62-12a17f6cb6c4.png)
During the make & install phase of the installation process in EPLA,this is gotten
![屏幕截图 2023-04-16 230933](https://user-images.githubusercontent.com/74701833/232322251-b48d5796-ffb1-4b2c-bf08-c8f52c7cd487.png)
During the Configure phase of the installation process in ABACUS, this is gotten.
![屏幕截图 2023-04-16 231108](https://user-images.githubusercontent.com/74701833/232322304-43530692-49af-4cb6-8027-a665dd38bf2a.png)
During the make phase of the installation process in ABACUS, this is gotten.
![屏幕截图 2023-04-16 231249](https://user-images.githubusercontent.com/74701833/232322474-34e653a6-6f3d-4981-8dfd-736a169de475.png)

which stage i had been wrong?

**Comment by A-006** [comment]
The installation tutorial provided on the official website uses elpa2021.05.002, but the code below will use a version of elpa equal to or greater than elpa2021.11.001. 
![屏幕截图 2023-04-18 184444](https://user-images.githubusercontent.com/74701833/232754081-2e9b2e61-86f8-4531-ade9-50fe833d0ea6.png)
Therefore, when downloading elpa, please pay attention to the version issue to avoid encountering the same error as mine.

![屏幕截图 2023-04-18 184652](https://user-images.githubusercontent.com/74701833/232754456-fbe03e74-5869-4300-9230-9bb1c14bd7d5.png)
It's possible that content from a version of elpa later than 2021.11.001 was used during compilation.

PS：The disk space usage and error rate for installing the libraries required for elpa directly on Ubuntu 22.04 are lower than those for using Intel oneAPI.

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
