### ISSUE TITLE
abacus crushed with HSE band calculation

### ISSUE THREAD

**Issue by zhang-changwei** [abacusmodeling/abacus-develop#273]
### Describe the bug

Black phosphorus primitive cell. HSE+DFT-D3(0) functional. I'm trying to run a scf cacluation with a gamma centered kmesh and several extra zero weight kpoints, just like what should be done in vasp.
However, abacus crushes even I only use one mpi process. If I change the functional to PBE, abacus seems work well.
Part of the output is showed as follows:
```
 -------------------------------------------
 SELF-CONSISTENT : 
 -------------------------------------------
 START CHARGE      : atomic
abacus: /public1/home/sch3658/src/ABACUS/abacus-develop_deepmodeling-develop/deps/LibRI/include/RI/physics/../distribute/Split_Processes.hpp:31: std::tuple<int, unsigned long> RI::Split_Processes::split(const int &, const unsigned long &): Assertion `rank_size>=group_size' failed.
```
The full input files are contained in the attachment.
[BP.zip](https://github.com/abacusmodeling/abacus-develop/files/11302918/BP.zip)

### Environment

abacus 3.2.0

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
