### ISSUE TITLE
Error when using Interface to Wannier90 by ABACUS

### ISSUE THREAD

**Issue by ProPLr00** [abacusmodeling/abacus-develop#279]
### Details

Hi developers, I am a beginner at DFT calculations and trying to use ABACUS to run the wannier90 program. I had succeeded in running the examples in the Interface_Wannier90 folder, but when I am trying with my own sample, it keeps coming out with the **_"Error real_lattice in *.nnkp file"_**. May I check with you about this? 

Thanks for your help in advance!

[wannier90_input.txt](https://github.com/abacusmodeling/abacus-develop/files/12381350/wannier90_input.txt)
[wannier90_nnkp.txt](https://github.com/abacusmodeling/abacus-develop/files/12381365/wannier90_nnkp.txt)
[STRU.txt](https://github.com/abacusmodeling/abacus-develop/files/12381366/STRU.txt)
[KPT2.txt](https://github.com/abacusmodeling/abacus-develop/files/12381367/KPT2.txt)
[KPT1.txt](https://github.com/abacusmodeling/abacus-develop/files/12381368/KPT1.txt)
[INPUT2.txt](https://github.com/abacusmodeling/abacus-develop/files/12381369/INPUT2.txt)
[INPUT1.txt](https://github.com/abacusmodeling/abacus-develop/files/12381370/INPUT1.txt)

**Comment by mohanchen** [comment]
Thanks! We suggest the issues can be raised in another repository, https://github.com/deepmodeling/abacus-develop/issues
