### ISSUE TITLE
The efficiency issues in running molecular dynamics simulations with the abacus 

### ISSUE THREAD

**Issue by JiajiaLiu7451** [abacusmodeling/abacus-develop#292]
### Details

给Ti的001面做分子动力学计算，计算总步长为500步，但是两天只跑了260步，并且在260步后任务意外中断。
[MD.zip](https://github.com/abacusmodeling/abacus-develop/files/13512543/MD.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by mohanchen** [comment]
Thanks! We suggest the issues be raised in another repository, https://github.com/deepmodeling/abacus-develop/issues
