### ISSUE TITLE
For large atomic systems calculate band structures

### ISSUE THREAD

**Issue by qlxu2015** [abacusmodeling/abacus-develop#293]
### Details

[large-system-band-soc.zip](https://github.com/abacusmodeling/abacus-develop/files/13523243/large-system-band-soc.zip)
大原子的二维材料体系，考虑soc算能带，经常爆内存，想问开发者有没有更好的建议：大体系（4000原子）大致需要多少算力，才能算得动。大体系还有其他优化性能的参数设置么。

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [ ] Identify the specific section of the code causing the performance issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

**Comment by mohanchen** [comment]
Thanks! We suggest the issues be raised in another repository, https://github.com/deepmodeling/abacus-develop/issues
