### ISSUE TITLE
Feature Request: Calculation of Second- and Third-Order Nonlinear Optical Properties

### ISSUE THREAD

**Issue by SchrodingersCattt** [abacusmodeling/abacus-develop#298]
Dear developers, 
Greetings!

We are encountering the need to calculate nonlinear optical properties and requesting your help.

We want the implementation of a feature within ABACUS that enables users to calculate the second- and third-order nonlinear optical properties of materials. This function should allow for the computation of key parameters such as the `second harmonic generation (SHG)`, `third harmonic generation (THG)`, `two-photon absorption (TPA)`, `Stimulated Raman Scattering (SRS)`, and `Kerr effects`, among others. Besides, this feature should encompass both frequency-dependent and -independent cases, providing a versatile platform for researchers to analyze multiple aspects of NLO phenomena.

Our research focuses on both small and mid-large systems (hundreds of atoms), so you might need to consider both KPOINT and band parallelization to avoid the problem of memory overflow.

You might consider referring to the code of `ABINIT` and `Yambo` with such features.

We would appreciate it if you consider our demand. We believe that adding these capabilities to ABACUS would not only greatly broaden the scope of its applicability but also enhance the value of ABACUS as a tool for cutting-edge research and industrial innovation in the field of nonlinear optics.

I would be deeply grateful for your help.

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
Hello, as suggested in https://github.com/abacusmodeling/abacus-develop/issues/274 , migrate this Issue to https://github.com/deepmodeling/abacus-develop/issues/3777
