### ISSUE TITLE
安装abacus更多功能出现问题。

### ISSUE THREAD

**Issue by liqiuyua** [abacusmodeling/abacus-develop#299]
### Details

1.我通过官网Install by conda只运行了conda create -n abacus_env abacus -c conda-forge进行安装，然后进入界面的高级安装指南打算安装更多功能。
2.在Build with Libxc下运行他给我的cmake -B build -DLibxc_DIR=~/libxc却显示没有source directory ~/build does not exist。但是按照Install by conda安装，前面我只需要一个命令，也没有和build有关的命令。这该怎么办，是哪里的问题呢？
罗马字母的第23个字母

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by dyzheng** [comment]
Hello, as suggested in https://github.com/abacusmodeling/abacus-develop/issues/274 , migrate this Issue to https://github.com/deepmodeling/abacus-develop/issues/3778
