### ISSUE TITLE
增加输出功能：输出每个原子的磁矩，极角和方位角

### ISSUE THREAD

**Issue by liqiuyua** [abacusmodeling/abacus-develop#302]
### Background

可以更好地和deeph联动起来，方便进行磁性材料计算。

### Describe the solution you'd like

希望增加功能

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by dyzheng** [comment]
Hello, as suggested in https://github.com/abacusmodeling/abacus-develop/issues/274 , migrate this Issue to https://github.com/deepmodeling/abacus-develop/issues/3865
