### ISSUE TITLE
关于锕系元素赝势及虚晶近似方法的建议

### ISSUE THREAD

**Issue by songruipku** [abacusmodeling/abacus-develop#318]
### Background

目前ABACUS轨道基组的赝势库中并不包含锕系元素，期待能够将这一部分发展出来。
其次，不知到能否发展基于轨道基组的虚晶近似方法（VCA）.
上述两个方面在应用上都很有施展空间，期待ABACUS能在此方向上发力！

### Describe the solution you'd like

锕系元素的赝势目前有比较好的PAW类型的（https://www.uni-marburg.de/de/fb15/arbeitsgruppen/anorganische_chemie/ag-kraus/forschung/paw-datasets-for-the-actinoids-dokumente/scalar-relativistic-basis.zip），不知能否以此为基础。
VCA方法希望能更像qe的模式，直接生成赝原子的赝势，这样可以进行后续其它譬如声子谱的计算。

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
