### ISSUE TITLE
Setting different value of OMP_NUM_THREADS results in the fail of simulation

### ISSUE THREAD

**Issue by Love-sea** [abacusmodeling/abacus-develop#319]
### Describe the bug

 For the same model, I ran simulations with the value (OMP_NUM_THREADS) set to 1 and 2, respectively, yielding drastically different results as shown in the figure below. When the parameter is set to 2, the simulation runs exceedingly slowly and generates a warning: "the movement of atom is larger than the length of cell," ultimately causing the simulation to terminate prematurely.

![1715848436601](https://github.com/abacusmodeling/abacus-develop/assets/95874948/06273554-d0a3-4299-991a-1b3cbd50d8b9)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
