### ISSUE TITLE
非自洽能带计算不输出波函数的bug

### ISSUE THREAD

**Issue by songruipku** [abacusmodeling/abacus-develop#321]
### Describe the bug

在算能带的时候，第一步自洽计算不设置out_wfc_lcao参数，第二步非自洽时设置out_wfc_lcao = 1，最后OUT文件夹里完全没有波函数输出。

### Expected behavior

希望在OUT中能有非自洽的波函数输出。

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
