### ISSUE TITLE
HSE calculation  is interrupted without  error reports

### ISSUE THREAD

**Issue by MumuMaster2021** [abacusmodeling/abacus-develop#323]
### Describe the bug

 96 atoms' scf calculation with hse and execute"OMP_NUM_THREADS=32 mpirun -np 1 abacus > log " ,After running for 20 minutes, the task failed . 
[m0-hse.tar.gz](https://github.com/user-attachments/files/15572617/m0-hse.tar.gz)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
