### ISSUE TITLE
nspin=4时，get_S将会没有输出

### ISSUE THREAD

**Issue by liqiuyua** [abacusmodeling/abacus-develop#327]
### Describe the bug

![586f17024b86ec65d973d56678b7d068](https://github.com/user-attachments/assets/fd594be8-540d-4789-9b5c-5cbf39866185)
输出SR.csr 文件如图所示

### Task list for Issue attackers (only for developers)

- [X] Verify the issue is not a duplicate.
- [X] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
