### ISSUE TITLE
abacus案例测试

### ISSUE THREAD

**Issue by meishengme** [abacusmodeling/abacus-develop#328]
### 运用abacustest进行abacus输入文件转换为qe输入文件计算时，转换失败或者qe无法正常运行的情况：

101_PW_15_paw：
运用abacustest将paw类型计算输入文件转换为qe文件时，没有指定赝势文件；

101_PW_blps_pseudopots：
qe无法正常读取赝势文件，报错赝势文件为空或错误

101_PW_upf201_uspp_NaCl、802_PW_LT_fcc、803_PW_LT_bcc、806_PW_LT_st、807_PW_LT_bct、810_PW_LT_fco：
qe运行报错
 
![图片1](https://github.com/user-attachments/assets/484c918c-f1ce-473b-b7a8-787d1ab4bce3)

105_PW_FD_smearing：
没有转换smearing参数导致qe运行报错

120_PW_KP_MD_NPT、 150_PW_15_CR_VDW3、 120_PW_KP_MD_NVT、 170_PW_MD_1O、170_PW_MD_2O、183_PW_MD_SDFT_10S、183_PW_MD_SDFT_5D10S、
183_PW_MD_SDFT_ALL：
结构优化和分子动力学类型计算，abacustest目前还无法实现abacus输入文件向qe输入文件的转换，无法生成qe的输入文件

### Task list for Issue attackers (only for developers)

- [ ] Understand the testing issue described by the developer.
- [ ] Review the specific test case, expected and actual results, and any error messages.
- [ ] Identify the root cause of the test failure or issue.
- [ ] If a possible solution is suggested, evaluate its feasibility and effectiveness.
- [ ] Implement a fix for the test failure or issue, or create a new test case if needed.
- [ ] Verify that the fix resolves the testing issue and the test case passes.
- [ ] Review and update any relevant documentation, such as test plans or user guides.
- [ ] Ensure the testing issue is resolved and close the ticket.
- [ ] Share any lessons learned or best practices with the team to prevent similar issues in the future.

**Comment by mohanchen** [comment]
Thanks for your advice, would you like to propose a new issue on deepmodeling/abacus?(https://github.com/deepmodeling/abacus-develop) We will discuss issues there.
