### ISSUE TITLE
I need CDFT

### ISSUE THREAD

**Issue by liqiuyua** [abacusmodeling/abacus-develop#332]
### Background

我想要把deeph和abacus结合起来做研究

### Describe the solution you'd like

我需要abacus的DFT可以限制磁矩的方向。deeph的人员是利用Openmx 的CDFT功能，所以开发者老师也可以参考一下这个软件的CDFT

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by mohanchen** [comment]
We will consider it, thanks.
