### ISSUE TITLE
稀土元素basis和pp

### ISSUE THREAD

**Issue by yabeiwu** [abacusmodeling/abacus-develop#333]
### Background

当前研究需要涉及一些稀土元素，但是开放渠道的基组和pp还没有稀土，可否提供？

### Describe the solution you'd like

我们需要的比如La，Ce，可否提供下载渠道？谢谢~

### Task list only for developers

- [ ] Notice possible changes of behavior
- [ ] Explain the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi

### Task list for Issue attackers (only for developers)

- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment]
@yabeiwu https://github.com/deepmodeling/abacus-develop/issues/3762

**Comment by yabeiwu** [comment]
> @yabeiwu [deepmodeling#3762](https://github.com/deepmodeling/abacus-develop/issues/3762)

thanks very much.

**Comment by kirk0830** [comment]
> > @yabeiwu [deepmodeling#3762](https://github.com/deepmodeling/abacus-develop/issues/3762)
> 
> thanks very much.

@yabeiwu later i recommend you submit any issue in this repo: https://github.com/deepmodeling/abacus-develop/issues, because here is not intentively maintained anymore.
