### ISSUE TITLE
Tests of SOC modulate

### ISSUE THREAD

**Issue by dyzheng** [abacusmodeling/abacus-develop#48]
**Is your feature request related to a problem? Please describe.**
The self-consistent calculation of DFT with spin-orbit coupling is always hard to converge. 
But usually, DFT without SOC can be easy to converge.
If we can modulate SOC effect, we might figure out how to get convergence with SOC on.

**Describe the solution you'd like**
* Now, SOC modulation method is implement in ABACUS (develop branch).
* Only SG15 and DOJO pseudopotential is supported.
* Set parameter "soc_lambda" in INPUT file to use that method. Double value from (0, 1).
* In fact, there are three method to implement SOC effect from full relativistic(FR) effect:
     * full soc method, read non-local part in pseudopotential directly and treat it. (need to use FR pseudopotential and set lspinorb as 1)
     * average SOC method, average non-local part with SOC to no SOC term, then treat it as no SOC calculation, quarter hamiltonian is calculated only. (FR and SR pseudopotential need to be same performance, set lspinorb as 0)
     * modulate SOC method, modulate non-local part with part of SOC effect. (need to use FR pseudopotential and set lspinorb as 1, set soc_lambda as value (0, 1))

**Additional context**
1. Test 1: use FR and SR pseudopotential with 'lspinorb=0' to do SCF calcualtion, check if the two results is correspond with each other.
2. Test 2: use FR pseudopotential with 'lspinorb=1' and 'soc_lambda = 0.0001 0.1 0.2 0.3 ...... 0.9 0.9999' to study the relation of Energy and soc_lambda, don't forget to check if soc_lambda = 0 and 1 is continuous.

**Put your test progress in comment of this issue please**

**Comment by 1041176461** [comment]
CsAgBiBr hse-soc calculation reports "Can't find even an electron!"

**Comment by 1041176461** [comment]
[CsAgBiBr-soc.zip](https://github.com/abacusmodeling/abacus-develop/files/7038948/CsAgBiBr-soc.zip)
HSE-SOC calculation for CsAgBiBr reports "Can't find even an electron!"

**Comment by dyzheng** [comment]
> [CsAgBiBr-SG15.zip](https://github.com/abacusmodeling/abacus-develop/files/7065867/CsAgBiBr-SG15.zip)
> upload example again

#56 in this PR, the bug reported is fixed.
