### ISSUE TITLE
The initial magnetic moment is set in STRU, but the magnetic moment is always zero during the electronic step iteration process.

### ISSUE THREAD

**Issue by jingan-181** [abacusmodeling/abacus-develop#99]
## Describe the Bug
 When doing a self-consistent calculation with soc, I set the initial magnetic moment in the STRU file, but during the running of the program, the total magnetism and absolute magnetism are always 0 0 0, which causes the calculation to fail to converge. And in the running_scf.log file, the magnetic moment information read is also zero.

## To Reproduce
1. git clone the latest ABACUS-develop branch on December 7, 2021.
2. use ABACUS to run the test case I uploaded.

## Environment
- OS: CentOS Linux release 7.6.1810 (Core)
- Compiler: intel compiler
- Optional Dependencies: intel mkl, elpa-2021.05.002

## test case
[MnBiTe.zip](https://github.com/abacusmodeling/abacus-develop/files/7674472/MnBiTe.zip)

**Comment by mohanchen** [comment]
For further discussions, we will move to https://github.com/deepmodeling/abacus-develop
